//
//  CountryMapping.swift
//  Ratatouille

import Foundation

struct CountryMapping {
    /// Translating the countrynames to countrycodes
    static let countryCodes: [String: String] = [
        "Afghan": "AF",
        "Albanian": "AL",
        "Algerian": "DZ",
        "Andorran": "AD",
        "Angolan": "AO",
        "Antiguan and Barbudan": "AG",
        "Argentinian": "AR",
        "Armenian": "AM",
        "Australian": "AU",
        "Austrian": "AT",
        "Azerbaijani": "AZ",
        "Bahamian": "BS",
        "Bahraini": "BH",
        "Bangladeshi": "BD",
        "Barbadian": "BB",
        "Belarusian": "BY",
        "Belgian": "BE",
        "Belizean": "BZ",
        "Beninese": "BJ",
        "Bhutanese": "BT",
        "Bolivian": "BO",
        "Bosnian and Herzegovinian": "BA",
        "Motswana": "BW",
        "Brazilian": "BR",
        "Bruneian": "BN",
        "Bulgarian": "BG",
        "Burkinabe": "BF",
        "Burundian": "BI",
        "Cabo Verdean": "CV",
        "Cambodian": "KH",
        "Cameroonian": "CM",
        "Central African": "CF",
        "Chadian": "TD",
        "Chilean": "CL",
        "Colombian": "CO",
        "Comoran": "KM",
        "Congolese": "CG",
        "Costa Rican": "CR",
        "Ivorian": "CI",
        "Cuban": "CU",
        "Cypriot": "CY",
        "Czech": "CZ",
        "Danish": "DK",
        "Djiboutian": "DJ",
        "Dominican": "DM",
        "Ecuadorian": "DO",
        "Salvadoran": "SV",
        "Equatorial Guinean": "GQ",
        "Eritrean": "ER",
        "Estonian": "EE",
        "Eswatini": "SZ",
        "Ethiopian": "ET",
        "Fijian": "FJ",
        "Finnish": "FI",
        "Gabonese": "GA",
        "Gambian": "GM",
        "Georgian": "GE",
        "German": "DE",
        "Ghanaian": "GH",
        "Grenadian": "GD",
        "Guatemalan": "GT",
        "Guinean": "GN",
        "Bissau-Guinean": "GW",
        "Guyanese": "GY",
        "Haitian": "HT",
        "Honduran": "HN",
        "Hungarian": "HU",
        "Icelandic": "IS",
        "Indonesian": "ID",
        "Iranian": "IR",
        "Iraqi": "IQ",
        "Israeli": "IL",
        "Jordanian": "JO",
        "Kazakhstani": "KZ",
        "Kiribatian": "KI",
        "North Korean": "KP",
        "South Korean": "KR",
        "Kosovar": "XK",
        "Kuwaiti": "KW",
        "Kyrgyz": "KG",
        "Laotian": "LA",
        "Latvian": "LV",
        "Lebanese": "LB",
        "Basotho": "LS",
        "Liberian": "LR",
        "Libyan": "LY",
        "Liechtensteiner": "LI",
        "Lithuanian": "LT",
        "Luxembourger": "LU",
        "Malagasy": "MG",
        "Malawian": "MW",
        "Maldivian": "MV",
        "Malian": "ML",
        "Maltese": "MT",
        "Marshallese": "MH",
        "Mauritanian": "MR",
        "Mauritian": "MU",
        "Micronesian": "FM",
        "Moldovan": "MD",
        "Monacan": "MC",
        "Mongolian": "MN",
        "Montenegrin": "ME",
        "Mozambican": "MZ",
        "Burmese": "MM",
        "Namibian": "NA",
        "Nauruan": "NR",
        "Nepalese": "NP",
        "New Zealander": "NZ",
        "Nicaraguan": "NI",
        "Nigerien": "NE",
        "Nigerian": "NG",
        "North Macedonian": "MK",
        "Norwegian": "NO",
        "Omani": "OM",
        "Pakistani": "PK",
        "Palauan": "PW",
        "Panamanian": "PA",
        "Peruvian": "PE",
        "Philippine": "PH",
        "Qatari": "QA",
        "Réunionese": "RE",
        "Romanian": "RO",
        "Serbian": "RS",
        "Rwandan": "RW",
        "Saudi Arabian": "SA",
        "Solomon Islander": "SB",
        "Seychellois": "SC",
        "Sudanese": "SD",
        "Swedish": "SE",
        "Singaporean": "SG",
        "Saint Helenian": "SH",
        "Slovenian": "SI",
        "Svalbardian and Jan Mayenite": "SJ",
        "Slovak": "SK",
        "Sierra Leonean": "SL",
        "American": "US",
        "British": "GB",
        "Canadian": "CA",
        "Chinese": "CN",
        "Croatian": "HR",
        "Dutch": "NL",
        "Egyptian": "EG",
        "Filipino": "PH",
        "French": "FR",
        "Greek": "GR",
        "Indian": "IN",
        "Irish": "IE",
        "Italian": "IT",
        "Jamaican": "JM",
        "Japanese": "JP",
        "Kenyan": "KE",
        "Malaysian": "MY",
        "Mexican": "MX",
        "Moroccan": "MA",
        "Polish": "PL",
        "Portuguese": "PT",
        "Russian": "RU",
        "Spanish": "ES",
        "Thai": "TH",
        "Tunisian": "TN",
        "Turkish": "TR",
        "Unknown": "Unknown",
        "Vietnamese": "VN"
    ]
}
